allowBuilds:
  esbuild: true
  msgpackr-extract: true
  workerd: true

overrides:
  effect: 4.0.0-rc.112
  '@effect/platform-node': 4.0.0-rc.112
  '@effect/platform-node-shared': 4.0.0-rc.112
  '@effect/sql-d1': 4.0.0-rc.112
  '@effect/sql-sqlite-do': 4.0.0-rc.112
  '@effect/vitest': 4.0.0-rc.112
