import { defineBuild } from "./define-build";

export default defineBuild({
  id: "arcane-assassin",
  title: "Arcane Assassin",
  description: "A written Arcane Assassin build and equipment checklist for Baldur's Gate 3 Patch 8.",
  heroDescription:
    "A stealth archer that opens with six attacks, automatic critical hits against surprised enemies, and four Arcane Shots per short rest.",
  class: "Gloom Stalker Ranger / Assassin Rogue / Arcane Archer Fighter",
  levelSplit: "Ranger 5 / Rogue 4 / Fighter 3",
  intro:
    "Start as a Gloom Stalker Ranger, add Assassin for surprise-round critical hits, then finish with Arcane Archer for Action Surge and control arrows.",
  levelNote: "Take Ranger through level 5, Rogue through level 9, then Fighter for the final three levels.",
  tags: ["Ranged", "Stealth", "Critical hits"],
  source: "https://www.youtube.com/watch?v=z9bliAD1fiA",
  sourceLabel: "Watch Toyhouze's source video",
  updated: "2026-09-17",
  creation: [
    { label: "Race", value: "Duergar" },
    { label: "Background", value: "Player choice" },
    { label: "Start", value: "Ranger" },
  ],
  abilities: { STR: 8, DEX: 17, CON: 16, INT: 8, WIS: 14, CHA: 10 },
  primaryAbility: "DEX",
  creationNotes: [
    { label: "Bonuses", text: "+2 DEX, +1 CON. Use Auntie Ethel's Hair for +1 DEX." },
    {
      label: "Duergar",
      text: "Enlarge adds damage without concentration, while the level-5 racial Invisibility helps begin encounters with Surprise.",
    },
    {
      label: "Dark Urge option",
      text: "The Deathstalker Mantle is available only to the Dark Urge. Other origins should use the Cloak of Displacement.",
    },
  ],
  combat: [
    "Cast Longstrider after each long rest. Before an ambush, use Enlarge and maintain Hunter's Mark or Pass Without Trace to activate the Strange Conduit Ring.",
    "Approach while invisible or hidden and attack to inflict Surprise. Assassin's Alacrity restores the action used to enter combat, and Assassin's Ambush makes later hits against surprised enemies critical hits.",
    "Combine Extra Attack, Dread Ambusher, and Action Surge for six opening attacks before most enemies can act.",
    "Use Shadow Arrow to blind a priority target, Banishing Arrow to remove a dangerous enemy for two turns, and Bursting Arrow for unavoidable force damage against a group.",
    "After each long rest, have a party member use the Drakethroat Glaive's Draconic Elemental Weapon on the Titanstring Bow. Keep a strength boost active through the Club of Hill Giant Strength or an elixir.",
  ],
  levels: [
    { classLevel: "Ranger 1", choice: "Duergar; Favoured Enemy and Natural Explorer" },
    { classLevel: "Ranger 2", choice: "Archery Fighting Style; Longstrider, Hunter's Mark" },
    {
      classLevel: "Ranger 3",
      choice: "Choose ",
      emphasis: "Gloom Stalker; Dread Ambusher, Disguise Self",
    },
    { classLevel: "Ranger 4", emphasis: "Feat: Sharpshooter" },
    {
      classLevel: "Ranger 5",
      choice: "Extra Attack; Misty Step, Pass Without Trace; Duergar Invisibility",
    },
    { classLevel: "Ranger 5 / Rogue 1", choice: "Sneak Attack, Expertise", secondary: true },
    {
      classLevel: "Ranger 5 / Rogue 2",
      choice: "Cunning Action: Dash, Disengage, and Hide",
      secondary: true,
    },
    {
      classLevel: "Ranger 5 / Rogue 3",
      choice: "Choose ",
      emphasis: "Assassin; Assassin's Alacrity, Initiative, and Ambush",
      secondary: true,
    },
    {
      classLevel: "Ranger 5 / Rogue 4",
      emphasis: "Feat: +2 DEX",
      secondary: true,
    },
    {
      classLevel: "Ranger 5 / Rogue 4 / Fighter 1",
      choice: "Defence Fighting Style, Second Wind",
      secondary: true,
    },
    {
      classLevel: "Ranger 5 / Rogue 4 / Fighter 2",
      choice: "Action Surge",
      secondary: true,
    },
    {
      classLevel: "Ranger 5 / Rogue 4 / Fighter 3",
      choice: "Choose ",
      emphasis: "Arcane Archer; Bursting Arrow, Banishing Arrow, and Shadow Arrow",
      secondary: true,
    },
  ],
  loadout: [
    { slot: "Main hand", item: "dolor-amarus" },
    { slot: "Off-hand", item: "dolor-amarus" },
    { slot: "Ranged", item: "titanstring-bow" },
    { slot: "Head", item: "helmet-of-arcane-acuity" },
    { slot: "Cloak · Any origin", item: "cloak-of-displacement" },
    { slot: "Cloak · Dark Urge", item: "the-deathstalker-mantle" },
    { slot: "Body", item: "armour-of-agility" },
    { slot: "Hands · Critical damage", item: "craterflesh-gloves" },
    { slot: "Hands · Accuracy", item: "legacy-of-the-masters" },
    { slot: "Feet", item: "helldusk-boots" },
    { slot: "Amulet", item: "broodmother-s-revenge" },
    { slot: "Ring", item: "caustic-band" },
    { slot: "Ring", item: "strange-conduit-ring" },
  ],
  equipment: [
    "gloves-of-archery",
    "caustic-band",
    "titanstring-bow",
    "club-of-hill-giant-strength",
    "broodmother-s-revenge",
    "strange-conduit-ring",
    "drakethroat-glaive",
    "yuan-ti-scale-mail",
    "helmet-of-arcane-acuity",
    "cloak-of-displacement",
    "the-deathstalker-mantle",
    "armour-of-agility",
    "craterflesh-gloves",
    "legacy-of-the-masters",
    "helldusk-boots",
    "dolor-amarus",
  ],
});
