import { defineBuild } from "./define-build";

export default defineBuild({
  id: "arcane-archer",
  title: "Arcane Archer",
  description: "A written Arcane Archer control build and equipment checklist for Baldur's Gate 3 Patch 8.",
  heroDescription:
    "A pure Fighter archer that banishes, blinds, frightens, and knocks enemies prone while stacking Arcane Acuity.",
  class: "Fighter",
  levelSplit: "Fighter 12",
  intro:
    "Stay with Arcane Archer Fighter for all 12 levels. The build combines Arcane Shots with reverberation and frightened to control entire encounters.",
  levelNote: "Take Fighter at every level. Dexterity comes first; raise Intelligence with the final feat.",
  tags: ["Ranged", "Control", "Reverberation"],
  source: "https://www.youtube.com/watch?v=kV0I0MM-hjA",
  sourceLabel: "Watch Toyhouze's source video",
  updated: "2026-09-17",
  creation: [
    { label: "Race", value: "High Half-Elf" },
    { label: "Background", value: "Player choice" },
    { label: "Start", value: "Fighter" },
  ],
  abilities: { STR: 12, DEX: 16, CON: 14, INT: 16, WIS: 8, CHA: 8 },
  primaryAbility: "DEX",
  creationNotes: [
    { label: "Bonuses", text: "+1 DEX, +2 INT." },
    { label: "Fighting Style", text: "Choose Archer for +2 to ranged weapon attack rolls." },
    {
      label: "High Half-Elf cantrip",
      text: "Choose Minor Illusion to group enemies before combat for Arrow of Many Targets.",
    },
  ],
  combat: [
    "Open with Arrow of Many Targets to stack Arcane Acuity, then use Banishing Arrow or Shadow Arrow with a higher save DC.",
    "Use the Amulet of the Harpers in Act II. In Act III, choose the Amulet of Bhaal to inflict Bleeding or the Amulet of the Devout for +2 Spell Save DC.",
    "Have a party member use the Drakethroat Glaive's Draconic Elemental Weapon on the Bow of the Banshee after each long rest. Choose thunder damage to enable the reverberation gear.",
    "Combine frightened from the Bow of the Banshee with prone from reverberation to prevent enemies from standing up.",
  ],
  levels: [
    { classLevel: "Fighter 1", choice: "Archer Fighting Style, Second Wind" },
    { classLevel: "Fighter 2", choice: "Action Surge" },
    {
      classLevel: "Fighter 3",
      choice: "Choose ",
      emphasis: "Arcane Archer; Guidance; Banishing Arrow, Shadow Arrow, and Piercing Arrow",
    },
    { classLevel: "Fighter 4", emphasis: "Feat: Sharpshooter" },
    { classLevel: "Fighter 5", choice: "Extra Attack" },
    { classLevel: "Fighter 6", emphasis: "Feat: +2 DEX" },
    { classLevel: "Fighter 7", choice: "Curving Shot, Magic Arrow, Seeking Arrow" },
    { classLevel: "Fighter 8", emphasis: "Feat: +2 DEX" },
    { classLevel: "Fighter 9", choice: "Indomitable" },
    { classLevel: "Fighter 10", choice: "Three additional Arcane Arrows, Grasping Arrow" },
    { classLevel: "Fighter 11", choice: "Improved Extra Attack" },
    { classLevel: "Fighter 12", emphasis: "Feat: +2 INT" },
  ],
  loadout: [
    { slot: "Main hand", item: "club-of-hill-giant-strength" },
    { slot: "Off-hand", item: "ketheric-s-shield" },
    { slot: "Ranged", item: "bow-of-the-banshee" },
    { slot: "Head", item: "helmet-of-arcane-acuity" },
    { slot: "Cloak", item: "thunderskin-cloak" },
    { slot: "Body", item: "armour-of-agility" },
    { slot: "Hands", item: "gloves-of-belligerent-skies" },
    { slot: "Feet", item: "boots-of-stormy-clamour" },
    { slot: "Amulet · Option A", item: "amulet-of-bhaal" },
    { slot: "Amulet · Option B", item: "amulet-of-the-devout" },
    { slot: "Ring", item: "ring-of-spiteful-thunder" },
    { slot: "Ring", item: "ring-of-absolute-force" },
  ],
  equipment: [
    "boots-of-stormy-clamour",
    "club-of-hill-giant-strength",
    "bow-of-the-banshee",
    "ring-of-absolute-force",
    "gloves-of-belligerent-skies",
    "yuan-ti-scale-mail",
    "amulet-of-the-harpers",
    "helmet-of-arcane-acuity",
    "thunderskin-cloak",
    "ring-of-spiteful-thunder",
    "drakethroat-glaive",
    "ketheric-s-shield",
    "armour-of-agility",
    "amulet-of-bhaal",
    "amulet-of-the-devout",
  ],
});
