import { defineBuild } from "./define-build";

export default defineBuild({
  id: "giant-thrower",
  title: "Giant Thrower",
  description: "A written min-maxed Giant Barbarian thrower build and equipment checklist for Baldur's Gate 3 Patch 8.",
  heroDescription:
    "A solo Honour Mode thrower that turns any weapon into a returning projectile and stacks critical-hit damage riders.",
  class: "Giant Barbarian / Champion Fighter",
  levelSplit: "Barbarian 9 / Fighter 3",
  intro:
    "Level as a Berserker through level 5. At level 6, respec into Giant Barbarian, then add three Champion Fighter levels before finishing Barbarian 9.",
  levelNote:
    "The final Barbarian level adds 2 damage to every Giant's Rage attack. For a safer solo variant, take Fighter 4 and Tough instead.",
  tags: ["Throwing", "Ranged", "Solo Honour Mode"],
  source: "https://www.youtube.com/watch?v=fDTYkU8pnd4",
  sourceLabel: "Watch Toxic Feather's source video",
  updated: "2026-09-17",
  creation: [
    { label: "Origin", value: "The Dark Urge" },
    { label: "Race", value: "Wood Half-Elf or Wood Elf" },
    { label: "Start", value: "Barbarian" },
  ],
  abilities: { STR: 8, DEX: 16, CON: 17, INT: 8, WIS: 10, CHA: 14 },
  primaryAbility: "CON",
  creationNotes: [
    {
      label: "Strength elixirs",
      text: "This solo setup dumps Strength and uses an Elixir of Hill Giant Strength. Without elixirs, start with 17 STR, 14 DEX, 16 CON, 8 INT, 8 WIS, and 10 CHA.",
    },
    {
      label: "Race",
      text: "Wood Elf and Wood Half-Elf provide extra movement. The Dark Urge origin supplies The Deathstalker Mantle for the solo route.",
    },
    {
      label: "Act I sword",
      text: "The source route obtains the Silver Sword of the Astral Plane early by forcing Kith'rak Voss to drop it before dialogue. This is optional and requires preparation.",
    },
  ],
  combat: [
    "Enter Giant's Rage, apply Elemental Cleaver to the weapon you intend to throw, and keep a critical-range or utility weapon in the off hand.",
    "Throw the Returning Pike before level 6. After Elemental Cleaver unlocks, use the Silver Sword, Shadow Blade, or Lightning Jabber for the encounter's damage type and riders.",
    "In Act II, cast Light with Guiding Light, then combine Callous Glow Ring, Luminous Armour, Gloves of Belligerent Skies, and Boots of Stormy Clamour for radiant and reverberation riders.",
    "In Act III, Bhaalist Armour doubles the Lightning Jabber's piercing damage. Craterflesh Gloves add repeated force damage on critical hits, while Rhapsody supplies its damage and critical-hit setup.",
    "Keep the Resonance Stone from the Mind Flayer Colony when using Shadow Blade; nearby creatures become vulnerable to its psychic damage.",
  ],
  levels: [
    { classLevel: "Barbarian 1", choice: "Rage, Unarmoured Defence" },
    { classLevel: "Barbarian 2", choice: "Reckless Attack, Danger Sense" },
    { classLevel: "Barbarian 3", emphasis: "Choose Berserker; Frenzy, Enraged Throw" },
    { classLevel: "Barbarian 4", emphasis: "Feat: Tavern Brawler, +1 CON" },
    { classLevel: "Barbarian 5", choice: "Extra Attack, Fast Movement" },
    {
      classLevel: "Barbarian 6",
      choice: "Respec and choose ",
      emphasis: "Giant; Elemental Cleaver",
    },
    { classLevel: "Barbarian 6 / Fighter 1", emphasis: "Dueling Fighting Style", secondary: true },
    { classLevel: "Barbarian 6 / Fighter 2", choice: "Action Surge", secondary: true },
    { classLevel: "Barbarian 6 / Fighter 3", emphasis: "Choose Champion", secondary: true },
    { classLevel: "Barbarian 7 / Fighter 3", choice: "Feral Instinct, Instinctive Pounce" },
    { classLevel: "Barbarian 8 / Fighter 3", emphasis: "Feat: Dual Wielder" },
    { classLevel: "Barbarian 9 / Fighter 3", choice: "Brutal Critical, increased Giant's Rage damage" },
  ],
  loadout: [
    { slot: "Main hand", item: "lightning-jabber" },
    { slot: "Off-hand", item: "rhapsody" },
    { slot: "Head", item: "helmet-of-grit" },
    { slot: "Cloak", item: "the-deathstalker-mantle" },
    { slot: "Body", item: "bhaalist-armour" },
    { slot: "Hands", item: "craterflesh-gloves" },
    { slot: "Feet", item: "helldusk-boots" },
    { slot: "Amulet", item: "amulet-of-greater-health" },
    { slot: "Ring", item: "ring-of-free-action" },
    { slot: "Ring", item: "shadow-cloaked-ring" },
  ],
  equipment: [
    "haste-helm",
    "hide-armour-2",
    "the-sparkle-hands",
    "moondrop-pendant",
    "boots-of-stormy-clamour",
    "boots-of-speed",
    "the-joltshooter",
    "bow-of-awareness",
    "returning-pike",
    "silver-sword-of-the-astral-plane",
    "caustic-band",
    "ring-of-flinging",
    "the-deathstalker-mantle",
    "knife-of-the-undermountain-king",
    "gloves-of-belligerent-skies",
    "shadow-blade-ring",
    "callous-glow-ring",
    "luminous-armour",
    "guiding-light",
    "surgeon-s-subjugation-amulet",
    "thunderskin-cloak",
    "marksmanship-hat",
    "ring-of-free-action",
    "shadow-cloaked-ring",
    "lightning-jabber",
    "craterflesh-gloves",
    "bhaalist-armour",
    "helldusk-boots",
    "amulet-of-greater-health",
    "rhapsody",
    "helmet-of-grit",
  ],
});
