import { defineBuild } from "./define-build";

export default defineBuild({
  id: "giant-thrower",
  title: "Giant Thrower",
  description: "A written min-maxed Giant Barbarian thrower build and equipment checklist for Baldur's Gate 3 Patch 8.",
  heroDescription:
    "A high-action thrower that combines Elemental Cleaver, the Thief's extra bonus action, and Action Surge.",
  class: "Giant Barbarian / Thief Rogue / Fighter",
  levelSplit: "Barbarian 6 / Rogue 4 / Fighter 2",
  intro:
    "Take six Giant Barbarian levels first for Extra Attack and Elemental Cleaver, then four Thief Rogue levels for Fast Hands and a feat before finishing with two Fighter levels for Defence and Action Surge.",
  levelNote:
    "Stay with Barbarian through level 6, then multiclass into Rogue and Fighter. Tavern Brawler and the level-10 Ability Improvement complete the core damage scaling.",
  tags: ["Throwing", "Ranged", "Action economy"],
  source: "https://hacktheminotaur.com/baldurs-gate-3/ultimate-bg3-giant-barbarian-build/",
  sourceLabel: "Read Hack the Minotaur's source guide",
  updated: "2026-09-18",
  creation: [
    { label: "Race", value: "Duergar Dwarf" },
    { label: "Background", value: "Soldier" },
    { label: "Start", value: "Barbarian" },
  ],
  abilities: { STR: 17, DEX: 16, CON: 15, INT: 8, WIS: 8, CHA: 8 },
  primaryAbility: "STR",
  creationNotes: [
    {
      label: "Race",
      text: "Duergar provides Superior Darkvision plus once-per-long-rest Enlarge and Invisibility. Enlarge adds damage and improves Strength checks.",
    },
    {
      label: "Bonuses",
      text: "Use Auntie Ethel's Hair for +1 STR. Tavern Brawler adds +1 CON, bringing both starting odd scores to even values.",
    },
    {
      label: "Strength elixirs",
      text: "Hill or Cloud Giant Strength elixirs remain excellent, but this version starts at 17 Strength and can reach 20 naturally.",
    },
  ],
  combat: [
    "Enter Giant's Rage, then apply Elemental Cleaver to the weapon you intend to throw. Choose lightning when an ally can make enemies Wet; otherwise choose the element that best fits the encounter.",
    "Use the Returning Pike until Elemental Cleaver unlocks. Upgrade to the Lightning Jabber in Act II and Nyrulna in Act III, allowing each weapon to return after a throw.",
    "Thief's Fast Hands supplies a second bonus action for Giant's Rage, mobility, potions, or Kick. Fighter's Action Surge adds another two throws once Extra Attack is active.",
    "In Act III, Bhaalist Armour doubles nearby enemies' piercing damage from Nyrulna. Ring of Flinging and Craterflesh Gloves add more damage to repeated throws.",
    "Nyrulna's explosion can also hit allies. Keep the Lightning Jabber available when friendly targets are standing close to the enemy.",
  ],
  levels: [
    { classLevel: "Barbarian 1", choice: "Rage, Unarmoured Defence" },
    { classLevel: "Barbarian 2", choice: "Reckless Attack, Danger Sense" },
    { classLevel: "Barbarian 3", emphasis: "Choose Giant; Giant's Rage, Thaumaturgy" },
    { classLevel: "Barbarian 4", emphasis: "Feat: Tavern Brawler, +1 CON" },
    { classLevel: "Barbarian 5", choice: "Extra Attack, Boot of the Giants" },
    { classLevel: "Barbarian 6", emphasis: "Elemental Cleaver" },
    { classLevel: "Barbarian 6 / Rogue 1", choice: "Expertise", secondary: true },
    { classLevel: "Barbarian 6 / Rogue 2", choice: "Cunning Action", secondary: true },
    { classLevel: "Barbarian 6 / Rogue 3", emphasis: "Choose Thief; Fast Hands", secondary: true },
    { classLevel: "Barbarian 6 / Rogue 4", emphasis: "Ability Improvement: +2 STR", secondary: true },
    {
      classLevel: "Barbarian 6 / Rogue 4 / Fighter 1",
      emphasis: "Defence Fighting Style",
      secondary: true,
    },
    { classLevel: "Barbarian 6 / Rogue 4 / Fighter 2", choice: "Action Surge", secondary: true },
  ],
  loadout: [
    { slot: "Main hand", item: "nyrulna" },
    { slot: "Ranged", item: "hellrider-longbow" },
    { slot: "Head", item: "sarevok-s-horned-helmet" },
    { slot: "Cloak", item: "cloak-of-protection" },
    { slot: "Body", item: "bhaalist-armour" },
    { slot: "Hands", item: "craterflesh-gloves" },
    { slot: "Feet", item: "helldusk-boots" },
    { slot: "Amulet", item: "amulet-of-greater-health" },
    { slot: "Ring", item: "ring-of-flinging" },
    { slot: "Ring", item: "killer-s-sweetheart" },
  ],
  equipment: [
    "haste-helm",
    "bloodguzzler-garb",
    "gloves-of-uninhibited-kushigo",
    "boots-of-genial-striding",
    "amulet-of-misty-step",
    "ring-of-flinging",
    "caustic-band",
    "returning-pike",
    "bow-of-awareness",
    "fistbreaker-helm",
    "cloak-of-protection",
    "enraging-heart-garb",
    "evasive-shoes",
    "surgeon-s-subjugation-amulet",
    "risky-ring",
    "lightning-jabber",
    "darkfire-shortbow",
    "killer-s-sweetheart",
    "sarevok-s-horned-helmet",
    "bhaalist-armour",
    "craterflesh-gloves",
    "helldusk-boots",
    "amulet-of-greater-health",
    "nyrulna",
    "hellrider-longbow",
  ],
});
