import { defineBuild } from "./define-build";

export default defineBuild({
  id: "ninja-assassin",
  title: "Ninja Assassin",
  description: "A written Ninja Assassin build and spoiler-conscious equipment checklist for Baldur's Gate 3.",
  heroDescription:
    "A quick Ninja Assassin leveling guide and a checklist for twenty-four items across all three acts.",
  class: "Shadow Monk / Assassin Rogue",
  levelSplit: "Monk 7 / Rogue 5",
  intro: "Follow this while leveling. The final split is Way of Shadow Monk 7 / Assassin Rogue 5.",
  levelNote: "Take Monk through level 7, then switch to Rogue.",
  tags: ["Stealth", "Melee", "High mobility"],
  source: "https://www.youtube.com/watch?v=6QOYYllhg_w",
  sourceLabel: "Watch the source video",
  updated: "2026-09-15",
  creation: [
    { label: "Race", value: "Wood Elf" },
    { label: "Background", value: "Charlatan" },
    { label: "Start", value: "Monk" },
  ],
  abilities: { STR: 8, DEX: 17, CON: 14, INT: 8, WIS: 16, CHA: 10 },
  primaryAbility: "DEX",
  creationNotes: [
    { label: "Bonuses", text: "+2 DEX, +1 WIS. Use Auntie Ethel's Hair for +1 DEX." },
    { label: "Skills", text: "Insight. Later, take Expertise in Stealth and Sleight of Hand." },
  ],
  combat: [
    "Start fights from stealth to trigger Surprise.",
    "Shadow Step for Advantage, then use Sneak Attack.",
    "Use Stunning Strike on threats. Hide or teleport out.",
  ],
  levels: [
    { classLevel: "Monk 1", choice: "Martial Arts, Flurry of Blows" },
    { classLevel: "Monk 2", choice: "Patient Defence, Step of the Wind" },
    { classLevel: "Monk 3", choice: "Choose ", emphasis: "Way of Shadow" },
    { classLevel: "Monk 4", emphasis: "Feat: +2 DEX" },
    { classLevel: "Monk 5", choice: "Extra Attack, Stunning Strike" },
    { classLevel: "Monk 6", choice: "Shadow Step" },
    { classLevel: "Monk 7", choice: "Evasion, Stillness of Mind" },
    { classLevel: "Rogue 1", choice: "Sneak Attack, Expertise", secondary: true },
    { classLevel: "Rogue 2", choice: "Cunning Actions", secondary: true },
    { classLevel: "Rogue 3", choice: "Choose ", emphasis: "Assassin", secondary: true },
    { classLevel: "Rogue 4", emphasis: "Feat: Savage Attacker", secondary: true },
    { classLevel: "Rogue 5", choice: "Uncanny Dodge, Sneak Attack 3d6", secondary: true },
  ],
  loadout: [
    { slot: "Main hand", item: "bloodthirst" },
    { slot: "Off-hand", item: "crimson-mischief" },
    { slot: "Ranged", item: "the-dead-shot" },
    { slot: "Head", item: "mask-of-soul-perception" },
    { slot: "Cloak", item: "shade-slayer-cloak" },
    { slot: "Body", item: "vest-of-soul-rejuvenation" },
    { slot: "Hands", item: "bonespike-gloves" },
    { slot: "Feet · Option A", item: "disintegrating-night-walkers" },
    { slot: "Feet · Option B", item: "bonespike-boots" },
    { slot: "Amulet", item: "sentient-amulet-very-rare", displayName: "Sentient Amulet" },
    { slot: "Ring", item: "killer-s-sweetheart" },
    { slot: "Ring", item: "ring-of-free-action" },
  ],
  equipment: [
    "ring-of-protection",
    "smuggler-s-ring",
    "disintegrating-night-walkers",
    "the-graceful-cloth",
    "knife-of-the-undermountain-king",
    "cloak-of-protection",
    "sword-of-life-stealing",
    "ring-of-free-action",
    "killer-s-sweetheart",
    "boots-of-uninhibited-kushigo",
    "bonespike-boots",
    "stalker-gloves",
    "sentient-amulet-very-rare",
    "khalid-s-gift",
    "shade-slayer-cloak",
    "mask-of-soul-perception",
    "vest-of-soul-rejuvenation",
    "the-dead-shot",
    "helldusk-gloves",
    "helldusk-helmet",
    "gloves-of-soul-catching",
    "bonespike-gloves",
    "crimson-mischief",
    "bloodthirst",
  ],
});
