import { defineBuild } from "./define-build";

export default defineBuild({
  id: "smite-swords-bard",
  title: "Smite Swords Bard",
  description: "A written Smite Swords Bard build and equipment checklist for Baldur's Gate 3 Patch 8.",
  heroDescription:
    "A melee control build that turns flourishes and area attacks into guaranteed critical Divine Smites.",
  class: "College of Swords Bard / Oath of Vengeance Paladin",
  levelSplit: "Bard 10 / Paladin 2",
  intro:
    "Level as a College of Swords Bard through level 7. At character level 8, respec into Paladin 2 / Bard 6, then take Bard to level 10.",
  levelNote: "The level-8 respec preserves Extra Attack while adding Divine Smite and Great Weapon Fighting.",
  tags: ["Melee", "Control", "Critical hits"],
  source: "https://www.youtube.com/watch?v=DiHyNzcqbGo",
  sourceLabel: "Watch Toyhouze's source video",
  updated: "2026-09-15",
  creation: [
    { label: "Race", value: "Half-Orc" },
    { label: "Background", value: "Entertainer" },
    { label: "Start", value: "Bard" },
  ],
  abilities: { STR: 12, DEX: 16, CON: 14, INT: 8, WIS: 8, CHA: 16 },
  primaryAbility: "CHA",
  creationNotes: [
    {
      label: "Skills",
      text: "Take Athletics, Deception, and Persuasion. At Bard 3, take Expertise in Persuasion and Deception.",
    },
    {
      label: "Level 1 spells",
      text: "Friends, Minor Illusion, Longstrider, Sleep, Tasha's Hideous Laughter, and Disguise Self.",
    },
    {
      label: "Level 8 respec",
      text: "Start Paladin with 16 STR, 8 DEX, 14 CON, 10 INT, 10 WIS, and 16 CHA. Gloves of Dexterity set DEX to 18. The Potion of Everlasting Vigour can raise STR to 18; Strength elixirs are the alternative.",
    },
  ],
  combat: [
    "Build Arcane Acuity with a weapon attack, then use the Band of the Mystic Scoundrel to cast Command or Hold Person as a bonus action.",
    "Attack held targets for automatic critical hits and add Divine Smite. Use Killer's Sweetheart with an area attack to critical-hit every target it catches.",
    "Use Edge of Darkness from Shar's Spear of Evening against groups. Bhaalist Armour doubles its piercing damage against nearby enemies.",
  ],
  levels: [
    { classLevel: "Bard 1", choice: "Bardic Inspiration; starting cantrips and spells" },
    { classLevel: "Bard 2", choice: "Healing Word, Jack of All Trades, Song of Rest" },
    {
      classLevel: "Bard 3",
      choice: "Choose ",
      emphasis: "College of Swords, Dueling, Hold Person",
    },
    { classLevel: "Bard 4", emphasis: "Light, Enhance Ability, Feat: Great Weapon Master" },
    { classLevel: "Bard 5", choice: "Glyph of Warding, Font of Inspiration, Bardic Inspiration d8" },
    { classLevel: "Bard 6", choice: "Extra Attack, Countercharm" },
    { classLevel: "Bard 7", choice: "Knock" },
    {
      classLevel: "Paladin 2 / Bard 6",
      choice: "Respec: Oath of Vengeance, Divine Smite, Great Weapon Fighting, Command",
      secondary: true,
    },
    { classLevel: "Paladin 2 / Bard 7", choice: "Knock", secondary: true },
    {
      classLevel: "Paladin 2 / Bard 8",
      emphasis: "See Invisibility, Feat: Savage Attacker",
      secondary: true,
    },
    { classLevel: "Paladin 2 / Bard 9", choice: "Hold Monster", secondary: true },
    {
      classLevel: "Paladin 2 / Bard 10",
      choice: "Dimension Door; Magical Secrets: Misty Step and Counterspell; Expertise in Performance and Deception",
      secondary: true,
    },
  ],
  loadout: [
    { slot: "Main hand", item: "shar-s-spear-of-evening" },
    { slot: "Ranged", item: "hellrider-longbow" },
    { slot: "Head", item: "helmet-of-arcane-acuity" },
    { slot: "Cloak", item: "cloak-of-the-weave" },
    { slot: "Body", item: "bhaalist-armour" },
    { slot: "Hands", item: "gloves-of-dexterity" },
    { slot: "Feet", item: "disintegrating-night-walkers" },
    { slot: "Ring", item: "risky-ring" },
    { slot: "Ring", item: "band-of-the-mystic-scoundrel" },
    { slot: "Ring · Swap in", item: "killer-s-sweetheart" },
  ],
  equipment: [
    "haste-helm",
    "hide-armour-2",
    "crusher-s-ring",
    "phalar-aluve",
    "gloves-of-the-growling-underdog",
    "disintegrating-night-walkers",
    "gloves-of-dexterity",
    "larethian-s-wrath",
    "yuan-ti-scale-mail",
    "cloak-of-protection",
    "risky-ring",
    "helmet-of-arcane-acuity",
    "callous-glow-ring",
    "killer-s-sweetheart",
    "shar-s-spear-of-evening",
    "hellrider-longbow",
    "band-of-the-mystic-scoundrel",
    "cloak-of-the-weave",
    "bhaalist-armour",
  ],
});
